### ISSUE TITLE
quesiton about Proxy Templates

### ISSUE THREAD

**Issue by empty-spacebar** [tum-vision/dbatk#3]
Hi.

I notice that your paper refer the paper[Proxy Templates for Inverse Compositional Photometric Bundle Adjustment], since it doesn't open source either, I wonder did you implement it in your code and found it useful?

I found that to accelerate the code many direct method odometry programs use inverse compositional algorithm on the frontend, but none of them on backend. So Proxy Templates arouses me quite a lot.

**Comment by NikolausDemmel** [comment]
Thanks for your interest. We did not use the inverse compositional method in BA. IIRC, upon closer inspection I was not convinced by the proxy templates approach. Compared to direct camera tracking, there is an inherent difficulty to deal with the changing depth value for photometric BA, when it comes to the IC formulation. But I never tried to actually implement it, so it might very well be I didn't fully understand it. But it could make sense to try it!

**Comment by empty-spacebar** [comment]
Thanks for your reply, it helps me a lot.
I will assess Proxy Templates further more.
